application: gcdc2013-riskmap
version: 2
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(htm$|html$|css$|js$|png$))
  static_files: \1
  upload: (.*\.(htm$|html$|css$|js$|png$))
  application_readable: true

- url: .*
  script: index.php
